#!/bin/bash

printf "\n\e[0;32m🍣   Generating production-ready files...\e[0m\n\n"

# Set up the dist folder
rm -rf dist
mkdir dist
mkdir dist/static
cp robots.txt dist
cp static/favicon.ico dist/static
cp static/manifest.json dist/static
cp -r static/images dist/static

# Compiles Elm code and transpiles JS to ES5

printf "\n\e[0;32m🍣   Compiling...\e[0m\n\n"
# elm make --optimize --output=dist/elm.js src/Main.elm 
elm make --output=dist/elm.js src/Main.elm 

printf "\n\e[0;32m🍣   Transpiling to ES5...\e[0m\n\n"
./node_modules/.bin/babel static/js -d dist/static/js --presets=@babel/env

cmd/minify

printf "\n\e[0;32m🍣   Done! Production files ready in the dist folder\e[0m\n\n"
